// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phonebook.DataAccess.Modules;

namespace Phonebook.DataAccess.Migrations
{
    [DbContext(typeof(PhoneBookDbContext))]
    [Migration("20210210215121_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                  .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("Phonebook.Contracts.Models.PhoneBookEntries.PhonebookEntry", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Name");

                b.Property<int>("PhoneBookId");

                b.Property<string>("PhoneNumber");

                b.HasKey("Id");

                b.HasIndex("PhoneBookId");

                b.ToTable("PhoneBookEntries");
            });

            modelBuilder.Entity("Phonebook.Contracts.Models.PhoneBookEntries.Phonebooks", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Name");

                b.HasKey("Id");

                b.ToTable("PhoneBooks");
            });

            modelBuilder.Entity("Phonebook.Contracts.Models.PhoneBookEntries.PhonebookEntry", b =>
            {
                b.HasOne("Phonebook.Contracts.Models.PhoneBookEntries.Phonebooks", "PhoneBook")
                    .WithMany("PhoneBookEntries")
                    .HasForeignKey("PhoneBookId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
        }
    }
}
